[package]
name = "sql-clipboard"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
arboard = "3"
rfd = "0.15"
local-ip-address = "0.6"
tauri-plugin-autostart = "2"
tauri-plugin-global-shortcut = "2"

[profile.release]
opt-level = 2
lto = "thin"
codegen-units = 16
